export enum dataBaseErrors {
  DATABASE_ERROR = "DATABASE_ERROR",
  DATABASE_QUERY_ERROR = "DATABASE_QUERY_ERROR",
  DATABASE_NOT_FOUND = "DATABASE_NOT_FOUND",
  DATABASE_DUPLICATE = "DATABASE_DUPLICATE",
}
