export enum tokenErrors {
  TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_INVALID = "TOKEN_INVALID",
  TOKEN_NOT_CREATED = "TOKEN_NOT_CREATED",
  TOKEN_NOT_VERIFIED = "TOKEN_NOT_VERIFIED",
}
