export enum Roles {
  user = "user",
  masterAdmin = "masterAdmin",
  admin = "admin",
}
export enum UserErrors {
  EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND",
  INCORRECT_PASSWORD = "INCORRECT_PASSWORD",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_UNAUTHORIZED = "USER_UNAUTHORIZED",
}
export enum UserSuccess {
  USER_CREATED = "USER_CREATED",
  USER_DELETED = "USER_DELETED",
  USER_UPDATED = "USER_UPDATED",
  USER_FOUND = "USER_FOUND",
  USER_LOGGED = "USER_LOGGED",
  USER_LOGOUT = "USER_LOGOUT",
}
