import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Cover from "@/components/Cover"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "La casita de papel",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>
        <Cover>{children}</Cover>
      </body>
    </html>
  )
}
