import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Cover from "@/components/Cover"
import { cn } from "@/lib/utils"

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })

export const metadata: Metadata = {
  title: "La casita de papel",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="">
      <body
        className={cn("min-h-screen font-sans antialiased", inter.variable)}
      >
        <Cover>{children}</Cover>
      </body>
    </html>
  )
}
